name: Ruby Test Runner

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["2.7.4"]
    steps:
      - name: Check out the parent repository with student submission data
        uses: actions/checkout@v2
      - name: Extract the student submission repo from URL
        uses: actions/github-script@v5
        id: get-repo-name
        with:
          script: |
            const submission = require('./submission.json')
            const gitURL =  submission.checklist[0].result
            const regex = /(?:git@|https:\/\/)github.com[:/](.*)/g
            const repoName = regex.exec(gitURL)[1]
            return repoName
          result-encoding: string
      - name: Check out the repository with student code
        uses: actions/checkout@v2
        with:
          repository: ${{steps.get-repo-name.outputs.result}}
          path: submission
      - name: Report to LMS tests in progress
        uses: pupilfirst/actions/reporting@v1
        with:
          status: "in_progress"
          description: "The automated tests are in progress"
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
      - name: Install Ruby dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          working-directory: submission
          bundler-cache: true
      - name: Run tests on student submission
        working-directory: submission
        run: bundle exec ruby test.rb
      - name: Report to LMS the outcome of tests.
        uses: pupilfirst/actions/reporting@v1
        with:
          status: "completed"
          report_file_path: "submission/report.json"
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
