name: WD-201 | L2 Milestone

on:
  push:
    branches: ["submission-*"]

jobs:
  repo_check:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{steps.get-repo-name.outcome}}
      repoName: ${{steps.get-repo-name.outputs.result}}
    steps:
      - name: Check out the parent repository with student submission data
        uses: actions/checkout@v2
      - name: Extract the student submission repo from URL
        uses: actions/github-script@v5
        id: get-repo-name
        continue-on-error: true
        with:
          script: |
            const submission = require('./submission.json')
            const gitURL =  submission.checklist[0].result
            const regex = /(?:git@|https:\/\/)github.com[:\/]([a-zA-Z0-9\-_.]+\/[a-zA-Z0-9\-_.\/]+)$/g
            const repoName = regex.exec(gitURL)[1].replace(/.git$|\/$/, "")
            if (repoName.split("/").length == 2) {
              return repoName
            } else {
              throw "The submitted URL seems to be of a folder inside a repository"
            }
          result-encoding: string
      - name: Report invalid repository URL in submission
        if: steps.get-repo-name.outcome != 'success'
        uses: pupilfirst/actions/grading@v1
        with:
          fail_submission: true
          feedback: The submitted repository URL is either invalid or private. Please make sure that you submit a valid public repository URL and not a link to directory or branch.
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
  tests:
    needs: repo_check
    timeout-minutes: 5
    if: needs.repo_check.outputs.outcome == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the parent repository with student submission data
        uses: actions/checkout@v2
      - name: Check out the solutions repository
        uses: actions/checkout@v2
        continue-on-error: true
        id: checkout-solution-repo
        with:
          repository: pupilfirst/wd201-nodejs-solutions
          path: solution
      - name: Check out the repository with student code
        uses: actions/checkout@v2
        continue-on-error: true
        id: checkout-student-repo
        with:
          repository: ${{needs.repo_check.outputs.repoName}}
          path: submission
      - name: Report invalid repository URL in submission
        if: steps.checkout-student-repo.outcome != 'success'
        uses: pupilfirst/actions/grading@v1
        with:
          fail_submission: true
          feedback: The submitted repository URL is either invalid or private. Please make sure that you submit a valid public repository URL.
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
      - name: Copy test files to submission repo
        if: steps.checkout-student-repo.outcome == 'success'
        id: copy-submission-files
        continue-on-error: true
        run: |
          cp -r solution/l2/cypress submission
          cp solution/l2/cypress.config.js submission
          cp solution/l2/generateReportFromResults.js submission
          cp solution/l2/package-lock.json submission
          cp solution/l2/package.json submission
      - name: Check presence of required files
        id: check-submission-files
        continue-on-error: true
        run: |
          cat submission/index.js
          cat submission/home.html
          cat submission/project.html
          cat submission/registration.html
      - name: Report missing files to the student
        if: steps.check-submission-files.outcome != 'success'
        uses: pupilfirst/actions/grading@v1
        with:
          fail_submission: true
          feedback: It seems like there are one or more missing files in your submitted repository. Please ensure that your repository has all the required files as per the milestone specifications.
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
      - name: Run tests in the solution repo
        continue-on-error: true
        id: run-cypress-test
        if: steps.copy-submission-files.outcome == 'success'
        run: |
          cd submission
          npm install
          npm run test
      - name: Use Node.js to generate report
        id: generate-report
        continue-on-error: true
        run: |
          cd submission && node generateReportFromResults.js
      - name: Grade the submission based on test results
        uses: pupilfirst/actions/grading@v1
        if: steps.generate-report.outcome == 'success'
        with:
          report_file_path: "submission/report.json"
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
