name: WD201 Node.js - L7 Milestone

on:
  push:
    branches: ["submission-*"]

env:
  REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
  REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}

jobs:
  extract_url:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{steps.get-submission-url.outcome}}
      submissionUrl: ${{steps.get-submission-url.outputs.result}}
    steps:
      - name: Check out the parent repository with student submission data
        uses: actions/checkout@v2
      - name: Extract the student submission URL
        uses: actions/github-script@v5
        id: get-submission-url
        continue-on-error: true
        with:
          script: |
            const submission = require('./submission.json')
            return submission.checklist[1].result
          result-encoding: string
      - name: Report invalid repository URL in submission
        if: steps.get-submission-url.outcome != 'success'
        uses: pupilfirst/grade-action@v1
        with:
          fail_submission: true
          feedback: We failed to extract the URL for your live web application from your submission. Please submit again; if this issue persists, please reach out to our team for support.
  tests:
    needs: extract_url
    timeout-minutes: 10
    if: needs.extract_url.outputs.outcome == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student repo and verify its structure
        id: check-student-repo
        uses: pupilfirst/check-repo-action@v1
        with:
          repoPath: submission
          globs: |-
            .gitignore
            hello-world/*
            http-server/*
            todo-cli/*
            todo-app/__tests__/todos.js
            todo-app/.husky/pre-commit
            todo-app/models/index.js
            todo-app/models/todo.js
            todo-app/migrations/*-create-todo.js
            todo-app/public/css/styles.css
            todo-app/views/footer.ejs
            todo-app/views/header.ejs
            todo-app/views/index.ejs
            todo-app/views/todos.ejs
            todo-app/app.js
            todo-app/index.js
            todo-app/package.json
            todo-app/package-lock.json
      - name: Report to LMS that tests are in progress
        if: steps.check-student-repo.outputs.result == 'success'
        uses: pupilfirst/report-action@v1
        with:
          status: "in_progress"
          description: "Automated tests are in progress"
      - name: Check out the repository with solutions and tests
        if: steps.check-student-repo.outputs.result == 'success'
        id: checkout-solutions-repo
        uses: actions/checkout@v2
        with:
          repository: "pupilfirst/wd201-tests"
          path: solution
      - name: Hack to run cypress on root
        if: steps.checkout-solutions-repo.outcome == 'success'
        run: |
          cp solution/l7/package.json package.json
          cp solution/l7/package-lock.json package-lock.json
      - name: Cypress run with env
        if: steps.checkout-solutions-repo.outcome == 'success'
        uses: cypress-io/github-action@v4
        continue-on-error: true
        timeout-minutes: 2
        with:
          browser: chrome
          project: ./solution/l7
          env: STUDENT_SUBMISSION_URL=${{needs.extract_url.outputs.submissionUrl}}
      - name: Use Node.js to generate report
        if: steps.checkout-solutions-repo.outcome == 'success'
        run: |
          cd solution/l7 && node generateReportFromResults.js
      - name: Grade the submission based on test results
        if: steps.checkout-solutions-repo.outcome == 'success'
        uses: pupilfirst/grade-action@v1
        with:
          report_file_path: "solution/l7/report.json"
      - name: Report to LMS the outcome of tests.
        if: steps.checkout-solutions-repo.outcome == 'success'
        uses: pupilfirst/report-action@v1
        with:
          report_file_path: "solution/l7/report.json"
