name: WD-201 | L2 Milestone

on:
  push:
    branches: ["submission-*"]

env:
  REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
  REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}

jobs:
  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student repo and verify its structure
        id: check-student-repo
        uses: pupilfirst/actions/check_repo@v1
        with:
          repoPath: submission
          globs: |-
            .gitignore
            hello-world/*
            http-server/index.js
            http-server/home.html
            http-server/package.json
            http-server/project.html
            http-server/registration.html
      - name: Check out the solutions repo
        if: ${{ steps.check-student-repo.outputs.result == 'success' }}
        id: checkout-solutions-repo
        uses: actions/checkout@v2
        with:
          repository: pupilfirst/wd201-nodejs-solutions
          path: solution
      - name: Copy test files to submission repo
        if: steps.checkout-solutions-repo.outcome == 'success'
        continue-on-error: true
        run: |
          cp -r solution/l2/cypress submission/http-server
          cp solution/l2/cypress.config.js submission/http-server
          cp solution/l2/generateReportFromResults.js submission/http-server
          cp solution/l2/package-lock.json submission/http-server
          cp solution/l2/package.json submission/http-server
      - name: Run tests in the solution repo
        if: steps.checkout-solutions-repo.outcome == 'success'
        continue-on-error: true
        id: run-cypress-test
        run: |
          cd submission/http-server
          npm install
          npm run test
      - name: Use Node.js to generate report
        if: steps.checkout-solutions-repo.outcome == 'success'
        id: generate-report
        continue-on-error: true
        run: |
          cd submission/http-server && node generateReportFromResults.js
      - name: Grade the submission based on test results
        uses: pupilfirst/actions/grading@v1
        if: steps.generate-report.outcome == 'success'
        with:
          report_file_path: "submission/http-server/report.json"
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
