name: WD-201 | L9 Milestone | Test

on:
  push:
    branches: ["submission-*"]

jobs:
  repo_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the parent repository with student submission data
        uses: actions/checkout@v2
      - name: Extract the student submission repo from URL
        uses: actions/github-script@v5
        id: get-repo-name
        continue-on-error: true
        with:
          script: |
            const submission = require('./submission.json')
            const gitURL =  submission.checklist[1].result
            const regex = /(?:git@|https:\/\/)github.com[:\/]([a-zA-Z0-9\-_.]+\/[a-zA-Z0-9\-_.\/]+)$/g
            const repoName = regex.exec(gitURL)[1].replace(/.git$|\/$/, "")
            if (repoName.split("/").length == 2) {
              return repoName
            } else {
              throw "The submitted URL seems to be of a folder inside a repository"
            }
          result-encoding: string
      - name: Report invalid repository URL in submission
        if: steps.get-repo-name.outcome != 'success'
        uses: pupilfirst/actions/grading@v1
        with:
          fail_submission: true
          feedback: The submitted repository URL is either invalid or private. Please make sure that you submit a valid public repository URL and not a link to directory or branch.
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
      - name: Check out the repository with student code
        uses: actions/checkout@v2
        if: steps.get-repo-name.outcome == 'success'
        continue-on-error: true
        id: checkout-student-repo
        with:
          repository: ${{steps.get-repo-name.outputs.result}}
          path: submission
          fetch-depth: 0
      - name: Report invalid repository URL in submission
        if: steps.checkout-student-repo.outcome != 'success'
        id: report-invalid-repo
        uses: pupilfirst/actions/grading@v1
        with:
          fail_submission: true
          feedback: The submitted repository URL is either invalid or private. Please make sure that you submit a valid public repository URL.
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
      - name: Get the count of commits
        id: get-commit-count
        if: steps.checkout-student-repo.outcome == 'success'
        run: |
          cd submission
          echo $(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
      - name: Check the count of commits and generate outcome
        uses: actions/github-script@v5
        id: check-repo-count
        continue-on-error: true
        with:
          script: |
            const count = ${{steps.get-commit-count.outputs.COMMIT_COUNT}}
            if (count >= 4) {
              return 'success'
            }
          result-encoding: string
      - name: Reporting insufficient commits in the repo
        if: steps.get-commit-count.outcome == 'success' && steps.check-repo-count.outputs.result != 'success'
        id: report-insufficient-commits
        uses: pupilfirst/actions/grading@v1
        with:
          fail_submission: true
          feedback: The submitted repository does not have enough commits to see the history of your work. You should submit the same repository from Level 6 and upwards. Please ensure that the submitted repository has at least four commits to show progression from previous levels.
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
