name: Wd-101 | Programming and Web Development Background

on:
  push:
    branches: ["submission-*"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.1.1"]
    steps:
      - name: Grade the submission based on test results
        uses: pupilfirst/actions/grading@v1
        with:
          report_file_path: "https://raw.githubusercontent.com/pupilfirst/vta-test-scripts/master/report/pass.json"
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
