name: Auto Grade Submission
on:
  push:
    branches: ["submission-*"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.1.1"]
    steps:
      - name: Check out the parent repository with student submission data
        uses: actions/checkout@v2
      - name: curl
        uses: wei/curl@v1
        with:
          args: -LJO https://raw.githubusercontent.com/pupilfirst/vta-test-scripts/master/report/pass.json
      - name: Grade the submission based on test results
        uses: pupilfirst/grade-action@v1
        with:
          report_file_path: "pass.json"
        env:
          REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
          REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
