name: WD301 - L5 Milestone

on:
  push:
    branches: ["submission-*"]

env:
  REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
  REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}

jobs:
  repo_check:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{steps.get-submission-url.outcome}}
      submissionUrl: ${{steps.get-submission-url.outputs.result}}
    steps:
      - name: Check out the parent repository with student submission data
        uses: actions/checkout@v2
      - name: Extract the student submission repo from URL
        uses: actions/github-script@v6
        id: get-submission-url
        continue-on-error: true
        with:
          script: |
            const submission = require('./submission.json')
            const netlifyUrl = submission.checklist[1].result
            if (netlifyUrl.includes("netlify.app")) {
              return netlifyUrl
            } else {
              throw "The submitted webpage URL seems to be invalid."
            }
          result-encoding: string
      - name: Report invalid webpage URL in submission
        if: steps.get-submission-url.outcome != 'success'
        uses: pupilfirst/grade-action@v1
        with:
          fail_submission: true
          feedback: |
            The URL you submitted is either invalid or does not look like a
            Netlify app URL. Please make sure that you submit the URL of an
            app hosted using Netlify, which should look something like this:
            `https://NAME.netlify.app`.
  tests:
    needs: repo_check
    if: needs.repo_check.outputs.outcome == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout student repo and verify its structure
        id: check-student-repo
        uses: pupilfirst/check-repo-action@v1
        with:
          repoPath: submission
          globs: |-
            .gitignore
            hello-react/*
            smarter-tasks/public/*
            smarter-tasks/src/hooks/useLocalStorage.ts
            smarter-tasks/src/App.tsx
            smarter-tasks/src/Header.tsx
            smarter-tasks/src/HomePage.tsx
            smarter-tasks/src/index.tsx
            smarter-tasks/src/NotFound.tsx
            smarter-tasks/src/ProtectedRoute.tsx
            smarter-tasks/src/Signin.tsx
            smarter-tasks/src/Task.tsx
            smarter-tasks/src/TaskApp.tsx
            smarter-tasks/src/TaskCard.css
            smarter-tasks/src/TaskDetailsPage.tsx
            smarter-tasks/src/TaskForm.tsx
            smarter-tasks/src/TaskList.tsx
            smarter-tasks/package.json
            smarter-tasks/package-lock.json
      - name: Report to LMS that tests are in progress
        if: steps.check-student-repo.outputs.result == 'success'
        uses: pupilfirst/report-action@v1
        with:
          status: in_progress
          description: Automated tests are in progress
      - name: Check out the tests repo
        if: steps.check-student-repo.outputs.result == 'success'
        uses: actions/checkout@v2
        id: checkout-tests-repo
        with:
          repository: pupilfirst/wd301-tests
          path: tests
      - name: Copy submission files to tests folder
        if: steps.checkout-tests-repo.outcome == 'success'
        id: copy-report-generator
        run: cp tests/helpers/generateReportFromResults.js tests/l5/generateReportFromResults.js
      - name: Run cypress tests
        continue-on-error: true
        if: steps.copy-report-generator.outcome == 'success'
        timeout-minutes: 2
        run: |
          cd tests/l5
          npm install
          npm run cy:run -- --env STUDENT_SUBMISSION_URL="${{needs.repo_check.outputs.submissionUrl}}"
      - name: Use Node.js to generate report
        if: steps.copy-report-generator.outcome == 'success'
        id: generate-report
        run: cd tests/l5 && node generateReportFromResults.js
      - name: Report to LMS the outcome of tests.
        if: steps.generate-report.outcome == 'success'
        uses: pupilfirst/report-action@v1
        id: report-test-results
        with:
          report_file_path: tests/l5/report.json
      - name: Grade the submission based on test results
        uses: pupilfirst/grade-action@v1
        if: steps.generate-report.outcome == 'success'
        with:
          report_file_path: tests/l5/report.json
      - name: Report error to LMS
        if: steps.report-test-results.outcome == 'skipped'
        uses: pupilfirst/report-action@v1
        with:
          status: "error"
          description: |
            Automated tests could not be run successfully. Please ask a member
            of the Pupilfirst team to look into this submission's VTA logs.
